
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erdem Ünlü
 */
public class KayitEkrani2 extends javax.swing.JFrame {
Kullanici_Islemleri methodlar = new Kullanici_Islemleri();
    /**
     * Creates new form KayitEkrani2
     */
    public KayitEkrani2() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TurSecimi1ComboBox_Alani = new javax.swing.JComboBox();
        TurSecimi2ComboBox_Alani = new javax.swing.JComboBox();
        TurSecimi3ComboBox_Alani = new javax.swing.JComboBox();
        SecimBitirButon_Alani = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FilmListeleme_Alani = new javax.swing.JTextArea();
        KaydiBitir_Alani = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kayit Ekrani");
        setBounds(new java.awt.Rectangle(600, 400, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("3 Tane sevdiginiz film turu seciniz:");

        TurSecimi1ComboBox_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TurSecimi1ComboBox_Alani.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aksiyon ve Macera", "Bilimkurgu ve Fantastik", "Romantik", "Drama", "Çocuk ve Aile", "Belgesel", "Komedi", "Korku", "Bilim ve Doğa", "Gerilim", "Anime", "Reality program" }));

        TurSecimi2ComboBox_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TurSecimi2ComboBox_Alani.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aksiyon ve Macera", "Bilimkurgu ve Fantastik", "Romantik", "Drama", "Çocuk ve Aile", "Belgesel", "Komedi", "Korku", "Bilim ve Doğa", "Gerilim", "Anime", "Reality program" }));

        TurSecimi3ComboBox_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TurSecimi3ComboBox_Alani.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aksiyon ve Macera", "Bilimkurgu ve Fantastik", "Romantik", "Drama", "Çocuk ve Aile", "Belgesel", "Komedi", "Korku", "Bilim ve Doğa", "Gerilim", "Anime", "Reality program" }));

        SecimBitirButon_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SecimBitirButon_Alani.setText("Secimi Bitir");
        SecimBitirButon_Alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecimBitirButon_AlaniActionPerformed(evt);
            }
        });

        FilmListeleme_Alani.setColumns(20);
        FilmListeleme_Alani.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        FilmListeleme_Alani.setRows(5);
        jScrollPane2.setViewportView(FilmListeleme_Alani);

        KaydiBitir_Alani.setBackground(new java.awt.Color(0, 0, 0));
        KaydiBitir_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KaydiBitir_Alani.setForeground(new java.awt.Color(255, 255, 255));
        KaydiBitir_Alani.setText("Kaydi Bitir");
        KaydiBitir_Alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydiBitir_AlaniActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Sectiginiz türlere gore en yuksek puan alan filmler:");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(SecimBitirButon_Alani))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TurSecimi2ComboBox_Alani, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TurSecimi3ComboBox_Alani, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TurSecimi1ComboBox_Alani, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KaydiBitir_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TurSecimi1ComboBox_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(TurSecimi2ComboBox_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(TurSecimi3ComboBox_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(SecimBitirButon_Alani))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(KaydiBitir_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SecimBitirButon_AlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecimBitirButon_AlaniActionPerformed
        String tur1 = TurSecimi1ComboBox_Alani.getSelectedItem().toString();
        String tur2 = TurSecimi2ComboBox_Alani.getSelectedItem().toString();
        String tur3 = TurSecimi3ComboBox_Alani.getSelectedItem().toString();
        String sonuc = methodlar.FilmListele(tur1);
        sonuc += "\n";
        sonuc += methodlar.FilmListele(tur2);
        sonuc += "\n";
        sonuc += methodlar.FilmListele(tur3);
        FilmListeleme_Alani.setText(sonuc);
        
        
        
    }//GEN-LAST:event_SecimBitirButon_AlaniActionPerformed

    private void KaydiBitir_AlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydiBitir_AlaniActionPerformed
            GirisEkrani girisekrani = new GirisEkrani();
            girisekrani.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_KaydiBitir_AlaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitEkrani2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea FilmListeleme_Alani;
    private javax.swing.JButton KaydiBitir_Alani;
    private javax.swing.JButton SecimBitirButon_Alani;
    private javax.swing.JComboBox TurSecimi1ComboBox_Alani;
    private javax.swing.JComboBox TurSecimi2ComboBox_Alani;
    private javax.swing.JComboBox TurSecimi3ComboBox_Alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
