
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erdem Ünlü
 */
public class KullaniciYonetimEkrani extends javax.swing.JFrame {
    Kullanici_Islemleri methodlar = new Kullanici_Islemleri();
    DefaultTableModel model;
    String KullaniciEmaili;
    String KullaniciSifresi;
    public int izlemeSuresi;
    public int ProgramUzunlugu;
    public int kullanici_ID;
    public int Program_ID;
    public int puan=0;
    public String Tarih;
    public int kaldigiBolum=1;
    public int ToplambolumSayisi;
    public int sayac = 0;
    /**
     * Creates new form KullaniciYonetimEkrani
     */
    public KullaniciYonetimEkrani() {
        initComponents();
        model =(DefaultTableModel) FilmTablosu_Alani.getModel();
        filmleriGetir();

        
    }
    
    public KullaniciYonetimEkrani(String email, String sifre){
        initComponents();
        KullaniciEmaili = email;
        KullaniciSifresi = sifre;
        model =(DefaultTableModel) FilmTablosu_Alani.getModel();
        filmleriGetir();
    }
    

   
    


 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        FilmTablosu_Alani = new javax.swing.JTable();
        icerikArama_Alani = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SectiginizFilm_Alani = new javax.swing.JTextField();
        FilmIzleButonu_Alani = new javax.swing.JButton();
        CikisYapButonu_Alani = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        puan_Alani = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        izlemeSuresi_alani = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bolum_Alani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ToplamBolumSayisi_Alani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BolumUzunlugu_Alani = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kullanici Yonetim Sayfasi");
        setBounds(new java.awt.Rectangle(600, 200, 0, 0));

        FilmTablosu_Alani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Program Adi", "Tur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FilmTablosu_Alani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilmTablosu_AlaniMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(FilmTablosu_Alani);
        if (FilmTablosu_Alani.getColumnModel().getColumnCount() > 0) {
            FilmTablosu_Alani.getColumnModel().getColumn(0).setResizable(false);
            FilmTablosu_Alani.getColumnModel().getColumn(1).setResizable(false);
        }

        icerikArama_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        icerikArama_Alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icerikArama_AlaniActionPerformed(evt);
            }
        });
        icerikArama_Alani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                icerikArama_AlaniKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sectiginiz Film:");

        SectiginizFilm_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        FilmIzleButonu_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FilmIzleButonu_Alani.setText("Filmi izle");
        FilmIzleButonu_Alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmIzleButonu_AlaniActionPerformed(evt);
            }
        });

        CikisYapButonu_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CikisYapButonu_Alani.setText("Cikis Yap");
        CikisYapButonu_Alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CikisYapButonu_AlaniActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Filme Puanim:");

        puan_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tarih:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kaldiginiz dakika:");

        izlemeSuresi_alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Arama Cubugu:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kaldiginiz Bolum:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Toplam Bolum Sayisi:");

        ToplamBolumSayisi_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bolum Uzunlugu:");

        BolumUzunlugu_Alani.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(icerikArama_Alani, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SectiginizFilm_Alani)
                            .addComponent(FilmIzleButonu_Alani, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ToplamBolumSayisi_Alani, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(BolumUzunlugu_Alani)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puan_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bolum_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(izlemeSuresi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 11, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CikisYapButonu_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(icerikArama_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SectiginizFilm_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puan_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addComponent(FilmIzleButonu_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(izlemeSuresi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(bolum_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(BolumUzunlugu_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToplamBolumSayisi_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CikisYapButonu_Alani, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(108, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icerikArama_AlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icerikArama_AlaniActionPerformed
        
        
    }//GEN-LAST:event_icerikArama_AlaniActionPerformed
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        FilmTablosu_Alani.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }

    public void filmleriGetir(){
        model.setRowCount(0); //calısan tablosu her seferinde sıfırlanmış olur.
        ArrayList<Filmler> filmler = new ArrayList<Filmler>();
        filmler = methodlar.filmleriGetir();
        
        if(filmler != null){
           for(Filmler film : filmler){
               Object[] FilmEkle = {film.getProgramAdi(),film.getTurAdi()};
               model.addRow(FilmEkle);
               
           }
       }
        
    }
    private void icerikArama_AlaniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icerikArama_AlaniKeyReleased
        String ara = icerikArama_Alani.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_icerikArama_AlaniKeyReleased

    private void FilmTablosu_AlaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilmTablosu_AlaniMouseClicked
        int selectedrow = FilmTablosu_Alani.getSelectedRow();
        SectiginizFilm_Alani.setText(model.getValueAt(selectedrow, 0).toString());
        FilmIzleButonu_Alani.setEnabled(true); ///butona tekrar tiklayabilir.
    }//GEN-LAST:event_FilmTablosu_AlaniMouseClicked

    private void FilmIzleButonu_AlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmIzleButonu_AlaniActionPerformed
            String izlenecekFilm = SectiginizFilm_Alani.getText();
            kullanici_ID = methodlar.kullaniciBilgileriTut(KullaniciEmaili);
            Program_ID = methodlar.programIdBul(izlenecekFilm);
            FilmIzleButonu_Alani.setEnabled(false);///Butona tekrar tiklanmasi engellendi.
            if(!puan_Alani.getText().equals("")){
                puan = Integer.parseInt(puan_Alani.getText());
            }
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH);
            Tarih = sdf.format(jDateChooser1.getDate());
            String ProgramTipi = methodlar.programTipBul(izlenecekFilm);
            int izlenensure =methodlar.izlemeSuresiBul(kullanici_ID, Program_ID);
            ///izlemeSuresi_alani.setText(String.valueOf(izlenensure));
            izlemeSuresi = izlenensure;

            if(ProgramTipi.equals("Film")){
                kaldigiBolum = 1;
            }
            else{
                kaldigiBolum=methodlar.kalinanBolumuBul(kullanici_ID, Program_ID);
                if(kaldigiBolum == 0){
                    kaldigiBolum = 1;
                }
            }
            
            
            if(izlemeSuresi>0 || kaldigiBolum>1){
                methodlar.eskiyiSil(kullanici_ID, Program_ID, izlemeSuresi);
            }
            
            
           ProgramUzunlugu = methodlar.programUzunluguBul(Program_ID);
           BolumUzunlugu_Alani.setText(String.valueOf(ProgramUzunlugu));
           ToplambolumSayisi = methodlar.toplamBolumSayisiniBul(Program_ID);
           ToplamBolumSayisi_Alani.setText(String.valueOf(ToplambolumSayisi));
           
           ///izlemeSuresi_alani.setText(String.valueOf(ToplambolumSayisi));
           
            if(ProgramTipi.equals("Film")){
                bolum_Alani.setText(String.valueOf(kaldigiBolum));
         
            Timer timer = new Timer(50,null);
            timer.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    if(izlemeSuresi<ProgramUzunlugu){
                    izlemeSuresi++;
                    izlemeSuresi_alani.setText(String.valueOf(izlemeSuresi));
                    if(izlemeSuresi == ProgramUzunlugu){
                        UIManager.put("OptionPane.okButtonText", "Tamam.");
                        JOptionPane.showMessageDialog(KullaniciYonetimEkrani.this,"Film Bitti.");
                        ///setVisible(false);
                        timer.stop();
                    }
                    }
                                       
                }
            });
            timer.start();
            
            } 
            else{
                Timer timer = new Timer(50,null);
                timer.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    
                   if(kaldigiBolum<=ToplambolumSayisi){
                    izlemeSuresi++;
                    bolum_Alani.setText(String.valueOf(kaldigiBolum));
                    izlemeSuresi_alani.setText(String.valueOf(izlemeSuresi));
                    if((izlemeSuresi == ProgramUzunlugu) && (kaldigiBolum<ToplambolumSayisi)){
                        izlemeSuresi =0;
                        kaldigiBolum++;
                        
                        
                    }
                    


                   }
                   
                   if((izlemeSuresi == ProgramUzunlugu) && (kaldigiBolum == ToplambolumSayisi)){
                  UIManager.put("OptionPane.okButtonText", "Tamam.");    
                  JOptionPane.showMessageDialog(KullaniciYonetimEkrani.this,"Dizi Bitti.");
                  //setVisible(false);
                  timer.stop();
                   }
                }
                
            });
            timer.start();
            }
         
            ///burasi.setText(String.valueOf(kullanici_ID) );
            
         
        
           
    }//GEN-LAST:event_FilmIzleButonu_AlaniActionPerformed

    private void CikisYapButonu_AlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CikisYapButonu_AlaniActionPerformed
        methodlar.kullaniciProgramTablosuEkle(kullanici_ID, Program_ID, Tarih, izlemeSuresi, kaldigiBolum, puan);
        System.exit(0);
    }//GEN-LAST:event_CikisYapButonu_AlaniActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciYonetimEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciYonetimEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciYonetimEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciYonetimEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciYonetimEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BolumUzunlugu_Alani;
    private javax.swing.JButton CikisYapButonu_Alani;
    private javax.swing.JButton FilmIzleButonu_Alani;
    private javax.swing.JTable FilmTablosu_Alani;
    private javax.swing.JTextField SectiginizFilm_Alani;
    private javax.swing.JTextField ToplamBolumSayisi_Alani;
    private javax.swing.JTextField bolum_Alani;
    private javax.swing.JTextField icerikArama_Alani;
    private javax.swing.JTextField izlemeSuresi_alani;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField puan_Alani;
    // End of variables declaration//GEN-END:variables
}
